<?php
if (isset($_SESSION['user_name']) && $_SESSION['user_name'] === 'webadmin') {
?>

<h1>Agregar libro</h1>
<form action="agregarLibro" method="POST" class="my-4">
    <div class="row">
        <div class="col-3">
            <div class="form-group">
                <label>Título</label>
                <input required name="Titulo" type="text" class="form-control">
            </div>
        </div>

        <div class="col-3">
            <div class="form-group">
                <label>Saga</label>
                <input required name="Saga" type="text" class="form-control">
            </div>
        </div>

        <div class="col-3">
            <div class form-group">
                <label>Género</label>
                <input required name="Genero" type="text" class="form-control">
            </div>
        </div>

        <div class="col-3">
            <div class="form-group">
                <label>ID del Autor</label>
                <input required name="id_autor" type="text" class="form-control">
            </div>
        </div>

        <div class="col-3">
            <div class="form-group">
                <label>Fecha de Publicación Original</label>
                <input required name="Fecha_de_publicacion_original" type="text" class="form-control">
            </div>
        </div>

        <div class="col-3">
            <div class="form-group">
                <label>Fecha de Publicación en Traducción</label>
                <input required name="Fecha_de_publicacion_traduccion" type="text" class="form-control">
            </div>
        </div>

        <div class="col-3">
            <div class="form-group">
                <label>Editorial Original</label>
                <input required name="Editorial_original" type="text" class="form-control">
            </div>
        </div>

        <div class="col-3">
            <div class="form-group">
                <label>Editorial en Traducción</label>
                <input required name="Editorial_traduccion" type="text" class="form-control">
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>

<?php }
?>