<?php require 'templates/header.phtml' ?>

<div class=>
    <form method="POST" action="auth">
        <div class="form-group">
            <label for="user_name">Nombre de Usuario</label>
            <input type="text" required class="form-control" id="user_name" name="user_name" aria-describedby="user_nameHelp">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" required class="form-control" id="password" name="password">
        </div>

        <?php if ($error) : ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div> 

        <?php endif ?>
       
        <button type="submit" class="btn btn-primary mt-3">Entrar</button>
    </form>
</div>

<?php require 'templates/footer.phtml' ?>
